# Generated by Django 5.0.10 on 2024-12-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_descripcion_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='estrellas',
            field=models.PositiveIntegerField(),
        ),
    ]
